"""
backend/app/services/report_generator.py

High-fidelity PDF Consultation Report Generator for IP-SAKTI Sahayak.
Compiles LLM-generated conversation summaries, statutory classifications,
patentability assessments, and citation indices into publication-ready PDF reports.
"""

from datetime import datetime, timezone
import io
import logging
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger("ipsakti.services.report_generator")


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and print total page numbers (e.g. 'Page 1 of 3')."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Top Running Header (Pages 2+)
        if self._pageNumber > 1:
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(36, 756, 576, 756)
            self.drawString(36, 762, "IP-SAKTI Sahayak — AI Consultation Summary Report")
            self.drawRightString(576, 762, "Confidential & Decision Support")

        # Bottom Running Footer (All Pages)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(36, 45, 576, 45)
        
        timestamp_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        self.drawString(36, 32, f"Generated by IP-SAKTI Sahayak v2.0 • {timestamp_str}")
        self.drawRightString(576, 32, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class ConsultationPDFGenerator:
    """Generates styled PDF consultation dossiers from structured summary payloads."""

    def __init__(self):
        self._setup_styles()

    def _setup_styles(self):
        self.base_styles = getSampleStyleSheet()

        self.styles = {
            "DocTitle": ParagraphStyle(
                "DocTitle",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=18,
                leading=22,
                textColor=colors.HexColor("#065F46"),  # Deep Emerald
                alignment=0,
                spaceAfter=4,
            ),
            "DocSubtitle": ParagraphStyle(
                "DocSubtitle",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=10,
                leading=14,
                textColor=colors.HexColor("#047857"),
                spaceAfter=10,
            ),
            "MetaKey": ParagraphStyle(
                "MetaKey",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=8.5,
                leading=11,
                textColor=colors.HexColor("#475569"),
            ),
            "MetaVal": ParagraphStyle(
                "MetaVal",
                parent=self.base_styles["Normal"],
                fontName="Helvetica",
                fontSize=8.5,
                leading=11,
                textColor=colors.HexColor("#0F172A"),
            ),
            "SectionHeader": ParagraphStyle(
                "SectionHeader",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=12,
                leading=16,
                textColor=colors.HexColor("#065F46"),
                spaceBefore=12,
                spaceAfter=6,
            ),
            "SubSectionHeader": ParagraphStyle(
                "SubSectionHeader",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=10,
                leading=13,
                textColor=colors.HexColor("#1E293B"),
                spaceBefore=8,
                spaceAfter=4,
            ),
            "Body": ParagraphStyle(
                "Body",
                parent=self.base_styles["Normal"],
                fontName="Helvetica",
                fontSize=9,
                leading=13,
                textColor=colors.HexColor("#1E293B"),
                spaceAfter=6,
            ),
            "BodyBold": ParagraphStyle(
                "BodyBold",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=9,
                leading=13,
                textColor=colors.HexColor("#0F172A"),
            ),
            "CalloutText": ParagraphStyle(
                "CalloutText",
                parent=self.base_styles["Normal"],
                fontName="Helvetica",
                fontSize=8.5,
                leading=12,
                textColor=colors.HexColor("#1E293B"),
            ),
            "BadgeText": ParagraphStyle(
                "BadgeText",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=9,
                leading=11,
                textColor=colors.HexColor("#065F46"),
                alignment=1,
            ),
            "TableHeader": ParagraphStyle(
                "TableHeader",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=8.5,
                leading=11,
                textColor=colors.white,
            ),
            "TableCell": ParagraphStyle(
                "TableCell",
                parent=self.base_styles["Normal"],
                fontName="Helvetica",
                fontSize=8,
                leading=11,
                textColor=colors.HexColor("#1E293B"),
            ),
            "TableCellBold": ParagraphStyle(
                "TableCellBold",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=8,
                leading=11,
                textColor=colors.HexColor("#0F172A"),
            ),
            "Disclaimer": ParagraphStyle(
                "Disclaimer",
                parent=self.base_styles["Normal"],
                fontName="Helvetica-Oblique",
                fontSize=7.5,
                leading=10,
                textColor=colors.HexColor("#64748B"),
                spaceBefore=8,
            ),
        }

    def generate_report(
        self,
        summary_data: Dict[str, Any],
        conversation_title: str = "Ayurvedic Consultation",
        jurisdiction: str = "INDIA",
        conversation_id: Optional[str] = None,
    ) -> bytes:
        """
        Builds and returns a PDF document binary stream for the given summary payload.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=42,
            bottomMargin=54,
        )

        story = []

        # ---------------------------------------------------------------------
        # 1. Header & Title Banner
        # ---------------------------------------------------------------------
        story.append(Paragraph("IP-SAKTI SAHAYAK", self.styles["DocSubtitle"]))
        story.append(
            Paragraph(
                "Ayurvedic, Herbal & Traditional Innovation Consultation Report",
                self.styles["DocTitle"],
            )
        )
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#059669"), spaceBefore=4, spaceAfter=8))

        # Metadata Table
        ref_id = (conversation_id or "SESSION-LATEST")[:18]
        timestamp_str = datetime.now(timezone.utc).strftime("%d %B %Y, %H:%M UTC")

        meta_data = [
            [
                Paragraph("<b>Consultation Title:</b>", self.styles["MetaKey"]),
                Paragraph(conversation_title, self.styles["MetaVal"]),
                Paragraph("<b>Date & Time:</b>", self.styles["MetaKey"]),
                Paragraph(timestamp_str, self.styles["MetaVal"]),
            ],
            [
                Paragraph("<b>Active Jurisdiction:</b>", self.styles["MetaKey"]),
                Paragraph(jurisdiction.upper(), self.styles["MetaVal"]),
                Paragraph("<b>Reference ID:</b>", self.styles["MetaKey"]),
                Paragraph(ref_id, self.styles["MetaVal"]),
            ],
        ]

        meta_table = Table(meta_data, colWidths=[100, 170, 90, 180])
        meta_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#F1F5F9")),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ])
        )
        story.append(meta_table)
        story.append(Spacer(1, 12))

        # ---------------------------------------------------------------------
        # 2. Executive Summary Box
        # ---------------------------------------------------------------------
        exec_summary = summary_data.get("executive_summary") or "Comprehensive statutory and patentability deliberation executed."
        story.append(Paragraph("1. Executive Consultation Summary", self.styles["SectionHeader"]))
        
        exec_box_data = [[
            Paragraph(f"<b>Overview:</b> {exec_summary}", self.styles["CalloutText"])
        ]]
        exec_box = Table(exec_box_data, colWidths=[540])
        exec_box.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ECFDF5")),  # Light Emerald
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#A7F3D0")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ])
        )
        story.append(exec_box)
        story.append(Spacer(1, 10))

        # ---------------------------------------------------------------------
        # 3. Product Classification & Formulation Dossier
        # ---------------------------------------------------------------------
        prod_data = summary_data.get("product_classification", {})
        cat_name = prod_data.get("category") or "Patent-or-Proprietary Medicine"
        cat_reason = prod_data.get("classification_reason") or "Ayurvedic formulation analyzed under statutory framework."
        dosage_form = prod_data.get("dosage_form") or "Specified in consultation"
        ingredients = prod_data.get("ingredients") or []
        ing_str = ", ".join(ingredients) if isinstance(ingredients, list) else str(ingredients)
        therapeutic_claims = prod_data.get("therapeutic_claims") or prod_data.get("intended_use") or "Refer to formulation"

        story.append(Paragraph("2. Product Formulation & Statutory Classification", self.styles["SectionHeader"]))

        class_table_data = [
            [
                Paragraph("<b>Statutory Category:</b>", self.styles["TableCellBold"]),
                Paragraph(f"<b>{cat_name}</b>", self.styles["BadgeText"]),
            ],
            [
                Paragraph("<b>Formulation / Dosage:</b>", self.styles["TableCellBold"]),
                Paragraph(f"{dosage_form} (Ingredients: {ing_str})", self.styles["TableCell"]),
            ],
            [
                Paragraph("<b>Therapeutic Claims:</b>", self.styles["TableCellBold"]),
                Paragraph(therapeutic_claims, self.styles["TableCell"]),
            ],
            [
                Paragraph("<b>Classification Grounding:</b>", self.styles["TableCellBold"]),
                Paragraph(cat_reason, self.styles["TableCell"]),
            ],
        ]

        class_table = Table(class_table_data, colWidths=[140, 400])
        class_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F8FAFC")),
                ("BACKGROUND", (1, 0), (1, 0), colors.HexColor("#D1FAE5")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ])
        )
        story.append(class_table)
        story.append(Spacer(1, 10))

        # ---------------------------------------------------------------------
        # 4. Patentability & ABS Compliance Assessment
        # ---------------------------------------------------------------------
        patent_info = summary_data.get("patentability_assessment", {})
        abs_info = summary_data.get("abs_compliance", {})

        story.append(Paragraph("3. Legal & Patentability Analysis", self.styles["SectionHeader"]))

        sec3p_status = patent_info.get("section_3p_status") or "Traditional Knowledge exclusion assessed."
        sec3e_status = patent_info.get("section_3e_status") or "Synergy / efficacy proof required for proprietary ASU."
        patent_eligibility = patent_info.get("overall_eligibility") or "CONDITIONAL"

        legal_data = [
            [
                Paragraph("<b>Aspect</b>", self.styles["TableHeader"]),
                Paragraph("<b>Statutory Grounding & Assessment</b>", self.styles["TableHeader"]),
            ],
            [
                Paragraph("<b>Section 3(p) (Traditional Knowledge)</b>", self.styles["TableCellBold"]),
                Paragraph(sec3p_status, self.styles["TableCell"]),
            ],
            [
                Paragraph("<b>Section 3(e) (Synergism / Efficacy)</b>", self.styles["TableCellBold"]),
                Paragraph(sec3e_status, self.styles["TableCell"]),
            ],
            [
                Paragraph("<b>ABS (Biological Diversity Act)</b>", self.styles["TableCellBold"]),
                Paragraph(
                    abs_info.get("summary") or "State Biodiversity Board (SBB) / NBA approval required for commercial bio-resource use.",
                    self.styles["TableCell"],
                ),
            ],
            [
                Paragraph("<b>Overall Patent Eligibility</b>", self.styles["TableCellBold"]),
                Paragraph(f"<b>{patent_eligibility}</b>", self.styles["TableCellBold"]),
            ],
        ]

        legal_table = Table(legal_data, colWidths=[160, 380])
        legal_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#065F46")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ])
        )
        story.append(legal_table)
        story.append(Spacer(1, 10))

        # ---------------------------------------------------------------------
        # 5. Regulatory & Manufacturing Pathway
        # ---------------------------------------------------------------------
        reg_info = summary_data.get("regulatory_pathway", {})
        story.append(Paragraph("4. Regulatory & Licensing Roadmap", self.styles["SectionHeader"]))

        reg_data = [
            [
                Paragraph("<b>Dimension</b>", self.styles["TableHeader"]),
                Paragraph("<b>Prescribed Pathway & Requirements</b>", self.styles["TableHeader"]),
            ],
            [
                Paragraph("<b>Licensing Authority</b>", self.styles["TableCellBold"]),
                Paragraph(reg_info.get("licensing_authority") or "State Licensing Authority (AYUSH)", self.styles["TableCell"]),
            ],
            [
                Paragraph("<b>Statutory License / Form</b>", self.styles["TableCellBold"]),
                Paragraph(reg_info.get("license_form") or "Form 25-D (Drugs and Cosmetics Act, 1940 / Rule 158B)", self.styles["TableCell"]),
            ],
            [
                Paragraph("<b>Key Compliance Steps</b>", self.styles["TableCellBold"]),
                Paragraph(reg_info.get("compliance_steps") or "Standardization of raw materials, pilot batch testing, SBB prior intimation.", self.styles["TableCell"]),
            ],
        ]

        reg_table = Table(reg_data, colWidths=[140, 400])
        reg_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#047857")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ])
        )
        story.append(reg_table)
        story.append(Spacer(1, 10))

        # ---------------------------------------------------------------------
        # 6. Authoritative Citations & Live Prior Art Evidence
        # ---------------------------------------------------------------------
        citations = summary_data.get("citations") or []
        if citations:
            story.append(Paragraph("5. Authoritative Statutory & Scientific References", self.styles["SectionHeader"]))

            cite_rows = [
                [
                    Paragraph("<b>Source / Registry</b>", self.styles["TableHeader"]),
                    Paragraph("<b>Section / Reference</b>", self.styles["TableHeader"]),
                    Paragraph("<b>Key Provision / Record Title</b>", self.styles["TableHeader"]),
                ]
            ]

            for c in citations[:8]:
                src_name = c.get("source") or c.get("document_title") or "Statutory Law"
                sec_ref = c.get("section") or c.get("section_ref") or "General"
                title_snip = c.get("title") or c.get("snippet") or "Indexed Authority"
                if len(title_snip) > 90:
                    title_snip = title_snip[:90] + "..."

                cite_rows.append([
                    Paragraph(src_name, self.styles["TableCellBold"]),
                    Paragraph(sec_ref, self.styles["TableCell"]),
                    Paragraph(title_snip, self.styles["TableCell"]),
                ])

            cite_table = Table(cite_rows, colWidths=[150, 120, 270])
            cite_table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E293B")),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ])
            )
            story.append(cite_table)
            story.append(Spacer(1, 10))

        # ---------------------------------------------------------------------
        # 7. Next Steps & Statutory Disclaimer
        # ---------------------------------------------------------------------
        next_steps = summary_data.get("actionable_next_steps") or [
            "Prepare comparative research data demonstrating synergistic enhancement under Section 3(e).",
            "Submit prior intimation to State Biodiversity Board (Form I) for biological resources.",
            "Compile Form 25-D manufacturing license application with batch standardization protocols.",
        ]

        story.append(Paragraph("6. Actionable Next Steps", self.styles["SectionHeader"]))
        for idx, step in enumerate(next_steps, 1):
            story.append(Paragraph(f"<b>{idx}.</b> {step}", self.styles["Body"]))

        story.append(Spacer(1, 6))
        story.append(
            Paragraph(
                "<b>Statutory Disclaimer:</b> This consultation report is an automated AI-assisted legal & regulatory "
                "decision support summary generated under Ministry of Ayush decision guidelines. It is based on point-in-time "
                "statutory records and user-provided formulation facts. It does not constitute formal legal opinion or substitute "
                "for consultation with registered patent attorneys, State Licensing Authorities, or the National Biodiversity Authority.",
                self.styles["Disclaimer"],
            )
        )

        # Build PDF with NumberedCanvas
        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes


# Singleton PDF generator
consultation_pdf_generator = ConsultationPDFGenerator()
